# Generated by Django 2.1.7 on 2019-03-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('github_profile_link', models.URLField(blank=True, null=True)),
                ('bio', models.TextField()),
            ],
        ),
    ]
